services:
  web:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      BLOG_FOR_INVENTOS_DATABASE_PASSWORD: root
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@db:3306/blog_dev
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
  db:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_dev
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
 
    
      
volumes:
    mysql_data:
